"""WAF / IPS fingerprinting from HTTP response metadata.

The scanner only has response headers, server banner, title and status code to
work with (no body), but that is enough to recognize the common vendors that
sit in front of the engagement targets. Detecting them matters because a WAF
that silently blocks or rate-limits turns scan output into noise (uniform 403s,
catch-all redirects, truncated dir-enum) -- surfacing "you are being filtered"
prevents those results from being read as ground truth.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class WafSignature:
    vendor: str
    # substrings matched case-insensitively against the Server banner / webserver
    server: tuple[str, ...] = ()
    # response-header names whose mere presence indicates the vendor
    header_names: tuple[str, ...] = ()
    # header name -> value substring (matched case-insensitively)
    header_values: tuple[tuple[str, str], ...] = ()
    # Set-Cookie names that indicate the vendor
    cookies: tuple[str, ...] = ()
    # substrings matched case-insensitively against the page title
    titles: tuple[str, ...] = ()


@dataclass(frozen=True)
class WafDetection:
    vendor: str
    indicators: list[str] = field(default_factory=list)


# Ordered roughly by how distinctive the signatures are; all are evaluated.
WAF_SIGNATURES: tuple[WafSignature, ...] = (
    WafSignature(
        vendor="Fortinet FortiWeb/FortiGuard",
        server=("fortiweb", "fortigate"),
        cookies=("fortiwafsid",),
        titles=("web page blocked", "fortiguard"),
    ),
    WafSignature(
        vendor="Cloudflare",
        server=("cloudflare",),
        header_names=("cf-ray", "cf-mitigated"),
        cookies=("__cfduid", "__cf_bm"),
        titles=("attention required", "cloudflare"),
    ),
    WafSignature(
        vendor="F5 BIG-IP ASM",
        server=("big-ip", "bigip"),
        header_names=("x-wa-info",),
        cookies=("ts", "bigipserver", "f5_cspm"),
        titles=("the requested url was rejected",),
    ),
    WafSignature(
        vendor="Akamai",
        server=("akamaighost",),
        header_names=("x-akamai-transformed",),
        titles=("access denied", "reference #"),
    ),
    WafSignature(
        vendor="AWS WAF / CloudFront",
        server=("awselb", "cloudfront"),
        header_names=("x-amzn-requestid", "x-amzn-waf-action", "x-amz-cf-id"),
    ),
    WafSignature(
        vendor="Imperva Incapsula",
        header_names=("x-iinfo", "x-cdn"),
        header_values=(("x-cdn", "incapsula"),),
        cookies=("visid_incap", "incap_ses", "nlbi_"),
    ),
    WafSignature(
        vendor="ModSecurity",
        server=("mod_security", "modsecurity", "naxsi"),
        titles=("mod_security", "this error was generated by mod_security"),
    ),
    WafSignature(
        vendor="Sucuri CloudProxy",
        server=("sucuri/cloudproxy",),
        header_names=("x-sucuri-id", "x-sucuri-cache"),
        titles=("sucuri website firewall",),
    ),
    WafSignature(
        vendor="Barracuda",
        cookies=("barra_counter_session",),
        titles=("barracuda",),
    ),
    WafSignature(
        vendor="Citrix NetScaler",
        cookies=("ns_af", "citrix_ns_id", "nsc_"),
        header_values=(("via", "netscaler"),),
    ),
    WafSignature(
        vendor="Wallarm",
        server=("nginx-wallarm",),
        header_names=("x-wallarm-",),
    ),
)

# Generic "you've been blocked" page titles that indicate filtering even when
# the vendor cannot be pinned down. Conservative on purpose -- these are phrases
# a normal application page is unlikely to use as its title.
GENERIC_BLOCK_TITLES: tuple[str, ...] = (
    "request blocked",
    "access denied",
    "forbidden",
    "blocked by",
    "security policy",
    "request rejected",
    "your request has been blocked",
)


def _norm(value: object) -> str:
    return str(value or "").strip().casefold()


def detect_waf(
    *,
    webserver: str | None = None,
    title: str | None = None,
    response_headers: dict[str, str] | None = None,
    status_code: int | None = None,
) -> list[WafDetection]:
    """Return WAF/IPS detections inferred from response metadata.

    Each detection lists the concrete indicators that fired so the finding is
    auditable rather than a bare vendor guess.
    """
    server_text = _norm(webserver)
    title_text = _norm(title)
    headers = {str(name).strip().casefold(): _norm(val) for name, val in (response_headers or {}).items()}
    # Set-Cookie may arrive joined; treat the cookie header value as one blob.
    cookie_blob = headers.get("set-cookie", "")

    detections: list[WafDetection] = []
    for signature in WAF_SIGNATURES:
        indicators: list[str] = []
        for needle in signature.server:
            if needle in server_text:
                indicators.append(f"Server~{needle}")
        for header_name in signature.header_names:
            for present in headers:
                if present.startswith(header_name) or present == header_name.rstrip("-"):
                    indicators.append(f"header:{present}")
        for header_name, needle in signature.header_values:
            if needle in headers.get(header_name.casefold(), ""):
                indicators.append(f"{header_name}~{needle}")
        for cookie_name in signature.cookies:
            if cookie_name in cookie_blob:
                indicators.append(f"cookie:{cookie_name}")
        for needle in signature.titles:
            if needle in title_text:
                indicators.append(f"title~{needle}")
        if indicators:
            detections.append(WafDetection(vendor=signature.vendor, indicators=sorted(set(indicators))))

    if not detections and status_code in {403, 406, 429, 503}:
        for needle in GENERIC_BLOCK_TITLES:
            if needle in title_text:
                detections.append(
                    WafDetection(
                        vendor="Unknown WAF/IPS",
                        indicators=[f"status:{status_code}", f"title~{needle}"],
                    )
                )
                break

    return detections
